### ISSUE TITLE
UI Alerts missing on some pages

### ISSUE THREAD

**Issue by samuelgrant** [ssm-deepcove/website#135]
- [x] Settings
  - Footer Quick Links
- [ ] Media System
- [ ] Page systems

@jacksos101 Please edit this post with any other pages missing notifications

**Comment by samuelgrant** [comment]
I'm not quite sure why, but the alerts don't display in the Quick Links page

**Comment by jacksos101** [comment]
If you find any more missing ones let me know exactly where and I can fix them

**Comment by samuelgrant** [comment]
@jacksos101 Have you added alerts to the above page?

**Comment by samuelgrant** [comment]
Based on an internal discussion I believe this has been resolved for now
