### ISSUE TITLE
Broken on IE - doesn't support includes()

### ISSUE THREAD

**Issue by jacksos101** [ssm-deepcove/website#149]
IE doesn't support Array.prototype.includes (not to be confused with String.includes, but hey, it doesn't support that either).

I can't get polyfill code to work for some reason, it doesn't apply.

**Comment by samuelgrant** [comment]
I'm closing this issue, see: https://www.techradar.com/nz/news/microsoft-internet-explorer-dead-1995-to-2019-rip
