### ISSUE TITLE
Mobile CMS: Broken Code - Fix before merge to master

### ISSUE THREAD

**Issue by samuelgrant** [ssm-deepcove/website#150]
- [x] **Noticeboard:** The platform has a tendency to switch back to the browser when updating content @jacksos101 
- [x] **Mobile Phone:** Make the mobile phone scrollable accross all previews (Mimic Fact files) @jacksos101 
- [x] **Mobile Phone CMS:**  Hide nav options for uncompleted features (Overview, Guided Walks, Quizzes, Settings) @samuelgrant 
- [x] **Fact File:** View doesn't update correctly when enabling/disabling a fact file
- [x] **Fact File:** The line spacing for listen should match pronounce @samuelgrant 
- [x] **Fact File:** When creating a new fact file, the page crashed when entering the title.
---
- Adding a fourth image to a fact file didn't work, is this capped at three on the phone ?

**Comment by samuelgrant** [comment]
@MitchellQ - **Discover Deep Cove** Fixes
- [ ] Sort fact files on the index page  `A-Z`
- [ ] Switch the Prounce and Listen **ICONS** (Listen should have musical note, Pronounce should have the speaker)

**Comment by jacksos101** [comment]
We don't cap images to three. I was able to add more than three images to an existing entry and to a new entry. 

Can you describe what you do to get the issue?

**Comment by samuelgrant** [comment]
During tests with Mitchell last night, I tried adding a fourth image to the Kea. When he clicked "Check for Updates" his phone downloaded a new image, but it never showed up in the slide show on his phone.

The mobile App CMS did continue to show it as expected

**Comment by samuelgrant** [comment]
PR #153 has these features and is awaiting review.
